# Generated by Django 4.1 on 2022-11-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=25)),
                ('option2', models.CharField(max_length=25)),
                ('option3', models.CharField(max_length=25)),
                ('option4', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feed_poll', to='feed.feed')),
            ],
        ),
    ]
