# Generated by Django 4.1.3 on 2022-12-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_rename_option1_feedpoll_choice_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpoll',
            name='choice_3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='feedpoll',
            name='choice_4',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
